"""initial

Revision ID: 62ebbec127c2
Revises:
Create Date: 2026-03-22 17:23:06.428415

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "62ebbec127c2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create core tables: items, audit_log, llm_call_log."""
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS items (
          item_id TEXT PRIMARY KEY,
          message_id TEXT NOT NULL,
          status TEXT NOT NULL,
          confidence REAL NOT NULL,
          extraction_json TEXT NOT NULL,
          created_at TEXT NOT NULL,
          updated_at TEXT NOT NULL
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS audit_log (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          item_id TEXT NOT NULL,
          event_type TEXT NOT NULL,
          actor TEXT NOT NULL,
          details_json TEXT NOT NULL,
          created_at TEXT NOT NULL
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS llm_call_log (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          item_id TEXT,
          model TEXT NOT NULL,
          prompt_version TEXT NOT NULL,
          tokens_in INTEGER NOT NULL,
          tokens_out INTEGER NOT NULL,
          cost_usd REAL NOT NULL,
          latency_ms REAL NOT NULL,
          created_at TEXT NOT NULL
        )
        """
    )
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_items_message_id ON items(message_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_audit_item_id ON audit_log(item_id)"
    )


def downgrade() -> None:
    """Drop core tables."""
    op.execute("DROP INDEX IF EXISTS idx_audit_item_id")
    op.execute("DROP INDEX IF EXISTS idx_items_message_id")
    op.execute("DROP TABLE IF EXISTS llm_call_log")
    op.execute("DROP TABLE IF EXISTS audit_log")
    op.execute("DROP TABLE IF EXISTS items")
